name: just_the_tooltip2
description: A multi directional tooltip used to display any content with
  inbuilt support for list views
version: 0.0.12
homepage: https://github.com/hieplee2997/just_the_tooltip2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  golden_toolkit: ^0.13.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
